### ISSUE TITLE
Create Logo

### ISSUE THREAD

**Issue by emilianovaccaro** [emilianovaccaro/Tasky#3]
Design logo for our web app

**Comment by mirandaink01** [comment]
Done.
![logo](https://user-images.githubusercontent.com/54248698/188915608-b0370ab0-4d67-4e36-b5d0-ebd26a7e7113.svg)
![logo_banner](https://user-images.githubusercontent.com/54248698/188915612-9e78772c-2347-4930-9700-0a7c73fe5a85.svg)
